name: SCAN-ON-COMMIT

on:
  push:
    branches: [ '*' ]

jobs:

  get-matrix-values:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-var.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-var
        run: |
          content=`cat ./build-matrix.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=matrix::$content"
  
  build-images:
    runs-on: ubuntu-latest
    needs:  get-matrix-values
    strategy:
      matrix: ${{fromJSON(needs.get-matrix-values.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - id: setEnv
        name: Set Job env vars 
        run: |
          cat JOB.env >> $GITHUB_ENV
      - id: setImageDetails
        name: Set image name and latest tag
        run: |
          if [ ${{matrix.target}} = "production" ]
          then 
            echo "::set-output name=fullImageName::$IMAGE_NAME"
          else
            echo "::set-output name=fullImageName::$IMAGE_NAME-${{matrix.target}}"
          fi
          if [ ${{matrix.latest}} = true ]
          then 
            echo "::set-output  name=latestTag::--tag defradigital/$FULL_IMAGE_NAME:latest"
          else
            echo "::set-output  name=latestTag:: "
          fi
      - name: Build the Docker image
        run: |
          echo "full image name ${{steps.setImageDetails.output.fullImageName}}"
          if [ ${{matrix.target}} = "production" ]
          then 
            FULL_IMAGE_NAME="$IMAGE_NAME"
          else
            FULL_IMAGE_NAME="$IMAGE_NAME-${{matrix.target}}"
          fi
          if [ ${{matrix.latest}} = true ]
          then 
            LATEST_TAG="--tag defradigital/$FULL_IMAGE_NAME:latest"
          fi
          docker build . --file Dockerfile --no-cache \
          --target=${{ matrix.target }} \
          --build-arg DEFRA_VERSION=$DEFRA_VERSION \
          --build-arg BASE_VERSION=${{ matrix.runtimeVersion }}-$ALPINE_VERSION  \
          --tag defradigital/$FULL_IMAGE_NAME:$DEFRA_VERSION-dotnet${{ matrix.runTimeVersion }} \
          $LATEST_TAG
      - uses: anchore/scan-action@v1
        if: ${{ matrix.target == 'production' }}
        with:
          image-reference: defradigital/${{ env.IMAGE_NAME }}:${{ env.DEFRA_VERSION }}-dotnet${{ matrix.runtimeVersion }}
          fail-build: true
          custom-policy-path: ./anchore-policy.json
          include-app-packages: true

      - name: Archive anchore report
        if: ${{ failure() && matrix.target == 'production' }}
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports-dotnet-${{ matrix.runtimeVersion }}
          path: anchore-reports
