name: SCAN-ON-COMMIT

on:
  push:
    branches: [ '*' ]

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      buildMatrix: ${{ steps.set-var.outputs.buildMatrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-var
        run: |
          content=`cat ./build-matrix.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=buildMatrix::$content"
  use-vars:
    runs-on: ubuntu-latest
    needs: set-vars
    strategy:
      matrix: ${{fromJSON(needs.set-vars.outputs.buildMatrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: isLatest
        id: isLatest
        if:  matrix.latest
        run: "export EXTRA_TAG='--tag defradigital/dotnetcore:latest'" 
      - id: set-var
        run: |
          cat VERSION.env >> $GITHUB_ENV
          echo "tag is ${{matrix.runtimeVersion}}"
          echo "latest is ${{matrix.latest}}"
          echo "EXTRA_TAG is $EXTRA_TAG"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --no-cache --build-arg DEFRA_VERSION=$DEFRA_VERSION --build-arg BASE_VERSION=${{matrix.runtimeVersion}}-$ALPINE_VERSION  --tag defradigital/dotnetcore:$DEFRA_VERSION-dotnet${{matrix.runTimeVersion}} $EXTRA_TAG

 
