name: SCAN-ON-COMMIT

on:
  push:
    branches: [ '*' ]

jobs:
  get-matrix-values:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-var.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-var
        run: |
          content=`cat ./build-matrix.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=matrix::$content"
  build-images:
    runs-on: ubuntu-latest
    needs:  get-matrix-values
    strategy:
      matrix: ${{fromJSON(needs. get-matrix-values.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - id: setEnv
        name: Set Job env vars 
        run: |
          cat JOB.env >> $GITHUB_ENV
      - name: Build the Docker image
        run: |
          if [ ${{matrix.latest}} = true ]
          then 
            LATEST_TAG="--tag defradigital/$IMAGE_NAME:latest"
          fi
          docker build . --file Dockerfile --no-cache \
          --build-arg DEFRA_VERSION=$DEFRA_VERSION \
          --build-arg BASE_VERSION=${{ matrix.runtimeVersion }}-$ALPINE_VERSION  \
          --tag defradigital/$IMAGE_NAME:$DEFRA_VERSION-dotnet${{ matrix.runTimeVersion }} \
          $LATEST_TAG
