name: SCAN-ON-COMMIT

on:
  push:
    branches: [ '*' ]

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      buildMatrix: ${{ steps.set-var.outputs.buildMatrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-var
        run: |
          content=`cat ./build-matrix.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=buildMatrix::$content"
  use-vars:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - uses: actions/checkout@v2
      - id: set-var
        run: |
          echo "version is ${{fromJSON(needs.set-vars.outputs.buildMatrix).version}}"
