name: SCAN-ON-COMMIT

on:
  push:
    branches: [ '*' ]

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      buildMatrix: ${{ steps.set-var.outputs.buildMatrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set_var
        run: |
          content=`cat ./build-matrix.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=buildMatrix::$content"
  
  build-push:
    needs: set-vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: use_vars
      - run: |
          echo "version is ${{fromJson(needs.set_vars.outputs.buildMatrix).version}}"
