name: SCAN-ON-COMMIT

on:
  push:
    branches: [ '*' ]

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      buildMatrix: ${{ steps.set-var.outputs.buildMatrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-var
        run: |
          content=`cat ./build-matrix.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=buildMatrix::$content"
  use-vars:
    runs-on: ubuntu-latest
    needs: set-vars
    strategy:
      matrix: ${{fromJSON(needs.set-vars.outputs.buildMatrix)}}
    steps:
      - uses: actions/checkout@v2
      - id: setLatest
        run: |
          cat VERSION.env >> $GITHUB_ENV
          if [ ${{matrix.latest}} = "true" ]
          then 
            echo "::set-output name=latestTag::--tag defradigital/"$IMAGE_NAME":latest"
          else
            echo "::set-output name=latestTag:: "
          fi
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --no-cache \
          --build-arg DEFRA_VERSION=$DEFRA_VERSION \
          --build-arg BASE_VERSION=${{ matrix.runtimeVersion }}-$ALPINE_VERSION  \
          --tag defradigital/$IMAGE_NAME:$DEFRA_VERSION-dotnet${{ matrix.runTimeVersion }} \
          ${{ steps.setLatest.outputs.latestTag }}
