name: NIGHTLY-SCAN

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  anchore-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set scan environment variables
        run:  cat scan.env >> $GITHUB_ENV
      - name: Scan .NET Core docker image
        uses: anchore/scan-action@v1
        with:
          image-reference: defradigital/dotnetcore:${{ env.DEFRA_VERSION }}-dotnet${{ env.NETCORE_VERSION }}
          fail-build: true
          custom-policy-path: ./anchore-policy.json
          include-app-packages: true

      - name: Archive anchore report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports-dotnet
          path: anchore-reports
