name: SCAN-ON-COMMIT

on:
  push:
    branches: [ '*' ]

jobs:
  anchore-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set scan environment variables
        run:  cat scan.env >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file Dockerfile --no-cache --build-arg DEFRA_VERSION=$DEFRA_VERSION --build-arg BASE_VERSION=$NETCORE_VERSION-$ALPINE_VERSION --tag defradigital/dotnetcore:$DEFRA_VERSION-dotnet$NETCORE_VERSION
      - uses: anchore/scan-action@v1
        with:
          image-reference: defradigital/dotnetcore:${{ env.DEFRA_VERSION }}-dotnet${{ env.NETCORE_VERSION }}
          fail-build: true
          custom-policy-path: ./anchore-policy.json
          include-app-packages: true

      - name: Archive anchore report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports-dotnet-push
          path: anchore-reports
